## Import libraries

In [1]:
import pandas as pd
import numpy as np

# to be able to display all columns and all rows of the dataframe 
#   (now that we know this one is small, only 700 rows)
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
data_preprocessed = pd.read_csv('../../../../statistics/python/Absenteeism/Absenteeism_preprocessed.csv')
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1,4
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0,2
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1,2


## Logistic Regression
We will classify all rows into two classes:
 - excessively absent - those with absenteeism over the median
 - average absent - those with absenteeism equal or under the median.

In [3]:
#Calculate the median
data_preprocessed['Absenteeism Time in Hours'].median()

np.float64(3.0)

## Create the targets for machine learning
3 hours is the cut line.
Let's create the targets array with a value o 1 for those rows having absenteeism over 3.

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Excessive Absenteeism
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1,4,1
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0,2,0
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0,4,1
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1,2,0


### Verify that the targets are evenly distributed.
For a logistic regression up to 60-40 division is sufficiently even.

In [6]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

Make a checkpoint "data_with_targets"

In [7]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis=1)
data_with_targets.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Excessive Absenteeism
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1,1
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0,0
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0,1
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1,0


In [8]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs.head()

,Reason_1,Reason_2,Reason_3,Reason_4,None,Month,DayOfWeek,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,0,0,0,1,0,7,1,289,36,33,239.554,30,0,2,1
1,0,0,0,0,1,7,1,118,13,50,239.554,31,0,1,0
2,0,0,0,1,0,7,2,179,51,38,239.554,31,0,0,0
3,1,0,0,0,0,7,3,279,5,39,239.554,24,0,2,0
4,0,0,0,1,0,7,3,289,36,33,239.554,30,0,2,1


## Standardize data

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

In [11]:
class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self,x,y=None):
        self.scaler.fit(x[self.columns],y)
        self.mean_ = np.mean(x[self.columns])
        self.var_ = np.var(x[self.columns])
        return self

    def transform(self,x,y=None,copy=None):
        init_col_order=x.columns
        x_scaled = pd.DataFrame(self.scaler.transform(x[self.columns]),columns=self.columns)
        x_not_scaled = x.loc[:,~x.columns.isin(self.columns)]
        return pd.concat([x_not_scaled,x_scaled],axis=1)[init_col_order]

In [12]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'None', 'Month',
       'DayOfWeek', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [13]:
columns_to_scale = ['Month','DayOfWeek', 'Transportation Expense', 'Distance to Work', 'Age',
                    'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

In [14]:
#absenteeism_scaler = StandardScaler()
absenteeism_scaler = CustomScaler(columns_to_scale)
absenteeism_scaler.fit(unscaled_inputs)

TypeError: StandardScaler.__init__() takes 1 positional argument but 4 were given

In [13]:
scaled_inputs = absenteeisrm_scaler.transform(unscaled_inputs)

In [14]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [15]:
scaled_inputs.shape

(700, 15)

## Split and shuffle data

In [16]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8,shuffle=True, random_state=20)

In [24]:
print(x_train.shape, y_train.shape)

(560, 15) (560,)


In [25]:
print(x_test.shape, y_test.shape)

(140, 15) (140,)


## Logistic regression with SkLearn

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [27]:
reg = LogisticRegression()
reg.fit(x_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [28]:
reg.score(x_train, y_train)

0.7857142857142857

## Manually check the accuracy

In [29]:
# make the model classify the inputs and store the classification vector
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [30]:
#Compare clasiffication vector with the targets
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [31]:
# To view how many True we got (how many did the model classify correctly)
#      - count the correctly classified (those equal to the targets, those True in the comparison)
np.sum(model_outputs==y_train)

np.int64(440)

In [32]:
#      - count how many elements were classified
model_outputs.shape[0]

560

In [33]:
#      - Divide the correct by the total
np.sum(model_outputs==y_train)/model_outputs.shape[0]

np.float64(0.7857142857142857)

### Find intercept and coeficients

In [34]:
intercept = reg.intercept_
coeficients = reg.coef_
feature_name = unscaled_inputs.columns.values

In [39]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(coeficients)
summary_table

,Feature name,Coefficient
0,Reason_1,0.624318
1,Reason_2,0.025250
2,Reason_3,0.611953
3,Reason_4,-0.331296
4,None,-1.259171
5,Month,0.193879
6,DayOfWeek,-0.072987
7,Transportation Expense,0.740016
8,Distance to Work,-0.054389
9,Age,-0.214266


In [40]:
# Add the intercept at the beginning
summary_table.index = summary_table.index+1
summary_table.loc[0] = 'Intercept', reg.intercept_[0]
summary_table = summary_table.sort_index()
summary_table

,Feature name,Coefficient
1,Reason_1,0.624318
2,Reason_2,0.025250
3,Reason_3,0.611953
4,Reason_4,-0.331296
5,None,-1.259171
6,Month,0.193879
7,DayOfWeek,-0.072987
8,Transportation Expense,0.740016
9,Distance to Work,-0.054389
10,Age,-0.214266


In [42]:
summary_table['Odds_ratio']= np.exp(summary_table.Coefficient)
summary_table

,Feature name,Coefficient,Odds_ratio
0,Intercept,-0.316836,0.728450
1,Reason_1,0.624318,1.866972
2,Reason_2,0.025250,1.025572
3,Reason_3,0.611953,1.844029
4,Reason_4,-0.331296,0.717993
5,None,-1.259171,0.283889
6,Month,0.193879,1.213950
7,DayOfWeek,-0.072987,0.929613
8,Transportation Expense,0.740016,2.095969
9,Distance to Work,-0.054389,0.947063


In [45]:
summary_table.sort_values('Feature name', ascending=False)

,Feature name,Coefficient,Odds_ratio
8,Transportation Expense,0.740016,2.095969
4,Reason_4,-0.331296,0.717993
3,Reason_3,0.611953,1.844029
2,Reason_2,0.025250,1.025572
1,Reason_1,0.624318,1.866972
15,Pets,-0.352588,0.702866
5,None,-1.259171,0.283889
6,Month,0.193879,1.213950
0,Intercept,-0.316836,0.728450
13,Education,-0.146205,0.863981
